### ISSUE TITLE
添加语言基础板块

### ISSUE THREAD

**Issue by Ir1d** [OI-wiki/OI-wiki#1150]
:thinking: 似乎可以搞个语言基础（（

目前想到可以放的：
1. pascal 转 c++ 急救
2. python java 速成
3. c++ stl 使用（（可以把之前分散的整理到一起去

_Originally posted by @Ir1d in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDI3MjAyMDk4MQ==/comments/review_comment_

**Comment by ouuan** [comment]
```yaml
  - 语言基础:
    - 编辑工具: lang/editors.md
    - C++基础:
      - hello world!: lang/helloworld.md
      - 变量: lang/variable.md
      - 数组: lang/array.md
      - 结构体: lang/struct.md
      - 指针: lang/pointer.md
      - 循环: lang/loop.md
      - 分支: lang/branch.md
      - 函数: lang/function.md
    - C++标准库:
      - C++标准库简介: lang/csl/index.md
      - STL容器:
        - STL容器简介: lang/csl/container.md
        - 迭代器: lang/csl/iterator.md
        - 序列式容器: lang/csl/sequence-container.md
        - 关联式容器: lang/csl/associative-container.md
        - 无序关联式容器: lang/csl/unordered-container.md
        - 容器适配器: lang/csl/container-adapter.md
      - STL算法: lang/csl/algorithm.md
      - bitset: lang/csl/bitset.md
      - string: lang/csl/string.md
    - pb_ds:
      - 堆: lang/pb-ds/priority-queue.md
      - 平衡树: lang/pb-ds/tree.md
    - pascal转C++急救: lang/pascaltocpp.md
    - python速成: lang/python.md
```

qaq

**Comment by Tiger3018** [comment]
1. 分支应该放在循环前面？
  循环要多次检验，判断条件是否满足；而逻辑判断就可以在分支里先行提出。
2. _hello world!_ 可以看作语言简介 + 输入输出的板块？要不要考虑将**基础算法里面的文件输入输出**也放过来？
3. _函数_ -> （函数）递归
4. _结构体_ 放到最后？可以考虑同时扩展一下结构体函数，运算符重载
4. 第二级板块加一个 C++ 11 新特性 ？要不要在语言基础里面还介绍一下不同的头文件（和他们的功能，函数），卡常小技巧和在线文档扩展链接。

**Comment by Xeonacid** [comment]
@Tiger3018 > 结构体 放到最后？可以考虑同时扩展一下结构体函数，运算符重载

我觉得区分下结构体和类比较好，结构体页面只讲继承于C的那些东西怎么样，类相关可以另开页面
（虽然说C++中struct与class只有默认权限的差别，但是我认为合在一起叫结构体不利于之后（将来）C学习和OOP学习

**Comment by ouuan** [comment]
> 1. 分支应该放在循环前面？
>    循环要多次检验，判断条件是否满足；而逻辑判断就可以在分支里先行提出。
> 2. _hello world!_ 可以看作语言简介 + 输入输出的板块？要不要考虑将**基础算法里面的文件输入输出**也放过来？
> 3. _函数_ -> （函数）递归
> 4. _结构体_ 放到最后？可以考虑同时扩展一下结构体函数，运算符重载
> 5. 第二级板块加一个 C++ 11 新特性 ？要不要在语言基础里面还介绍一下不同的头文件（和他们的功能，函数），卡常小技巧和在线文档扩展链接。

1. 我是按照 C++ Primer Plus 的顺序来的。

2. 文件输入输出和 hello world 肯定不能放一起，但可以放到“C++基础”里。

3. 递归可以在函数这章简单提一下，详细的还是在[基础算法/递归 & 分治](https://oi-wiki.org//basic/divide-and-conquer/)。

4. 结构体指不带成员函数的，类则带成员函数/运算符重载，不讲继承之类的，因为在 OI 中用处不大。

5. C++ 11 新特性在相应版块标注即可，头文件的话除了基础的几个其它都在 “C++ 标准库” 里讲。

**Comment by TrisolarisHD** [comment]
？结构体还不能带成员函数和重载运算符了？

**Comment by ouuan** [comment]
> ？结构体还不能带成员函数和重载运算符了？

“指”指“指”不指“能”。

**Comment by Tiger3018** [comment]
貌似这个话题引向了 OI Wiki 应该怎么定位 x

我觉得还是在能让路人能看懂了解 + 学习的人能知道自己应该学些什么，遇到教材不懂的地方不用到处找口嗨的博客上面找均衡点。

2.3.没意见，1.可以不用拘束于一本书，4.5.成员函数、重载和新特性，个人认为还是得找个地方集中讲。

**Comment by Ir1d** [comment]
我整理了一下之前的一些想法，可能会有疏漏，欢迎指正

```
  - 语言基础:
    - 编辑工具: lang/editors.md
    - C++ 基础:
      - hello world!: lang/helloworld.md
      - 变量: lang/variable.md
      - 数组: lang/array.md
      - 结构体: lang/struct.md
      - 指针: lang/pointer.md
      - 分支: lang/branch.md
      - 循环: lang/loop.md
      - 函数: lang/function.md
    - C++ 标准库:
      - C++ 标准库简介: lang/csl/index.md
      - STL 容器:
        - STL 容器简介: lang/csl/container.md
        - 迭代器: lang/csl/iterator.md
        - 序列式容器: lang/csl/sequence-container.md
        - 关联式容器: lang/csl/associative-container.md
        - 无序关联式容器: lang/csl/unordered-container.md
        - 容器适配器: lang/csl/container-adapter.md
      - STL 算法: lang/csl/algorithm.md
      - bitset: lang/csl/bitset.md
      - string: lang/csl/string.md
    - C++ 进阶:
      - 类: lang/class.md
      - 新版 C++ 特性: lang/new.md
      - pb_ds:
        - 堆: lang/pb-ds/priority-queue.md
        - 平衡树: lang/pb-ds/tree.md
    - pascal 转 C++ 急救: lang/pascaltocpp.md
    - python 速成: lang/python.md
    - java 速成: lang/java.md
```

然后 comment 一下就是，我感觉没必要一步到位把所有东西分得很清晰.. 毕竟先整理一个粗糙的框架然后慢慢填东西会容易一些
