### ISSUE TITLE
[BUG] 关于在vscode 插件显示的bug

### ISSUE THREAD

**Issue by keywet06** [OI-wiki/OI-wiki#2774]
- [x] 我已经读过了 [F.A.Q.](https://oi-wiki.org/intro/faq/)，进行了搜索，但没有得到答案
- [x] 我正在着手修复这个问题

## 我遇到了这样的问题

在vscode扩展搜索出来的词条界面背景黑色，无法看见文字，能见度极低

## 我确认这个问题可以这样复现

使用vscode `OI Wiki` 扩展，搜索任意一个词条并点开（确保你的vscode是暗色系背景）

## 我认为这个问题可以这样解决

在 oi-wiki 的css文件中增加一行

```css
body {
    background-color: white;
}
```

或者改变扩展运作方式

## 备注

其实这个问题应该在扩展的项目提出，但由于应该需要在这个项目里解决，故在此提出
