### ISSUE TITLE
[RFC] 关于统一题目存储方式的讨论

### ISSUE THREAD

**Issue by Enter-tainer** [OI-wiki/OI-wiki#3518]
## 背景

为了实现代码在线运行和代码 CI 功能, 需要将代码, 测试数据与文档分开存储. 本 RFC 计划提出一种统一的存储格式, 可以方便代码在线运行, 代码 CI, 多语言代码展示等功能的后续实现.

## 内容

该格式的定义如下: https://github.com/EtherOJ/EtherTester/blob/master/problem.d.ts

使用时, 采用 yaml 格式, 如:

```yaml
version: 1000
id: 'oi-wiki:example/dnd'
name: 'Divide and Conquer Example 1'
target: ['!test']
solution:
  cpp: 'code/dnd.cpp'
  python: 'code/dnd.py' 
```

渲染效果为:

![photo_2021-09-07_18-14-15](https://user-images.githubusercontent.com/25521218/132327988-57145a31-3b96-4947-af78-d1796d2285da.jpg)

加入此功能后, 代码在线运行功能和代码 CI 功能可以从此文件读取输入数据和输出数据的路径, 并据此进行测试.
