### ISSUE TITLE
[功能请求] 禁止在正文中使用斜体中文

### ISSUE THREAD

**Issue by CCXXXI** [OI-wiki/OI-wiki#4779]
### 我遇到的问题是

目前部分页面使用了斜体中文进行排版，较不美观。

### 示例页面

[可持久化平衡树 - OI Wiki](https://oi-wiki.org/ds/persistent-balanced/)

![image](https://user-images.githubusercontent.com/25550534/224351953-55eeb54f-5b1c-40fb-a965-358c5dc76652.png)

### 参考

[用斜体排版中文是否合适？ - 知乎](https://www.zhihu.com/question/20120243)

### 我希望能有这样的解决方案

[既然汉字不适合斜体形式，在转译英文中表强调的斜体文字时，应该如何处理？ - 知乎](https://www.zhihu.com/question/20471777)

### 我觉得这些备选方案也可以接受

```css
i {
    font-style : normal;
    font-weight: bold;
}
```
