### ISSUE TITLE
[RFC] 优化 Mergify 的使用

### ISSUE THREAD

**Issue by yusancky** [OI-wiki/OI-wiki#6219]
## 背景

OI Wiki 使用 Mergify 以自动化 PR 合并流程。然而实际操作中 Mergify 几乎不被有效使用，按现在的逻辑与情况 Mergify 甚至不可能被触发。如果 OI Wiki 仍有计划使用 Mergify，需要进行一定优化调整。

## 预期效果

| PR 情况 | check 通过 | check 未完成 |
| :----: | :----: | :----: |
| 一个 approve 足够 | 手动合并／标记 Mergify label 后自动合并 | 标记 Mergify label 且 check 完成后自动合并 |
| 一个 approve 不足够 | 手动合并／`approve >= 2` 后自动合并 | `approve >= 2` 且 check 完成后自动合并 |

### 简化 label 使用

当前要求 PR 需要有 2 个 approve 且需要被标记特定的 label 才能自动合并。然而，手动合并通常只需要一个 approve，拥有 2 个 approve 往往可以被认为是审核已经足够。

建议取消在拥有 2 个 approve 时还需要有特定 label 的要求，等待第 2 个 approve 后 Mergify 可以直接自动合并。

### 更新检查和构建相关 Actions 判定条件

<details>

<summary>修改思路</summary>

- 对于 PR，目前判定的 LaTeX 构建工作流只对 `push` 生效，有需要替换为对于 PR 构建工作流使用的 `Incrementally Build LaTeX document`，否则 Mergify 将不可能工作。
- 对 CJK 的检查、对 Typst 的构建等新加入的工作流也应该进行检查判定。

</details>

事实上，OI Wiki 已经设置了 GitHub 分支保护，Mergify 会自动考虑这些因素（_随意打开一个 PR 的 Mergify Summary 页面就可以看到_），可以直接删除 `.mergify.yml` 中对 check 的判定。

## 参考代码

按以上描述，修改后的 <kbd>.mergify.yml</kbd> 如下：

<details>

<summary><kbd>.mergify.yml</kbd>（<a href="https://github.com/OI-wiki/OI-wiki/compare/master...yusancky:OI-wiki:patch-5#diff-6a30e47dd51449847422017b16878889b848f6602ac56d5a2e67ce8a19afade2"><code>diff</code></a>、<a href="https://github.com/OI-wiki/OI-wiki/compare/master...yusancky:OI-wiki:patch-5"><code>开启／查看拉取请求</code></a>）</summary>

```yaml
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "base=master"
      - "label!=Discussion / 需要讨论"
      - "label!=Pending review / 等待审核"
      - "label!=Waiting other PRs / 等待其它 PR"
      - "label!=Work in Progress / 施工中"
      - or:
        - "label=mergify/can-merge"
        - "#approved-reviews-by>=2"
    actions:
      merge:
        method: squash
```

</details>
